const https = require('https');
const fs = require('fs');
const path = require('path');
const express = require('express');

const app = express();
const PORT = 3000;

// Serve all static files from the project root
app.use(express.static(path.join(__dirname)));

// Try to load dev certs generated by office-addin-dev-certs
function getCerts() {
  const certDir = path.join(
    process.env.USERPROFILE || process.env.HOME,
    '.office-addin-dev-certs'
  );
  const keyPath  = path.join(certDir, 'localhost.key');
  const certPath = path.join(certDir, 'localhost.crt');

  if (fs.existsSync(keyPath) && fs.existsSync(certPath)) {
    return { key: fs.readFileSync(keyPath), cert: fs.readFileSync(certPath) };
  }
  return null;
}

const certs = getCerts();

if (certs) {
  https.createServer(certs, app).listen(PORT, () => {
    console.log(`\n✅ Data Matrix Add-in server running at https://localhost:${PORT}`);
    console.log('   Open Excel and load the add-in from Insert → Add-ins → Shared Folder');
    console.log('\n   Press Ctrl+C to stop.\n');
  });
} else {
  console.error('\n❌ SSL certificates not found.');
  console.error('   Run this command first, then restart:');
  console.error('   npm run install-cert\n');
  process.exit(1);
}
